### ISSUE TITLE
Add CMB support to WP-API

### ISSUE THREAD

**Issue by modemlooper** [WebDevStudios/CMB2#107]
The WP-API does not add meta to its data. It is up to plugins to add data they want exposed via JSON. Opening this issue to get support started.

**Comment by Ramblurr** [comment]
Any update on whether CMB supports WP-API?

I'm evaluating various custom fields plugins, and working support for WP-API is a must.

**Comment by jtsternberg** [comment]
@Ramblurr I've been asked that a couple times, but CMB2 simply uses post-meta. http://wp-api.org/#posts_retrieve-meta-for-a-post I don't think CMB2 needs any additional support.

**Comment by Ramblurr** [comment]
Thanks @jtsternberg  what about options on custom admin options pages?

**Comment by jtsternberg** [comment]
@Ramblurr that's a good question. WP-API doesn't support options (it appears). I'm assuming that is for security reasons since there is a lot of sensitive data stored in the options table. I'm checking in w/ the WP-API team to see if they have plans and why/why not.

**Comment by Ramblurr** [comment]
Thanks @jtsternberg 

A use case for you: A user has a Wordpress site and an Android app. They want to be able to update various things in the Android app from their Wordpress admin page. My plan is to create a custom admin page, expose the data with WP-API, then consume the JSON in the Android app.

**Comment by jtsternberg** [comment]
I totally get the use-case, but considering the security implications, making all CMB2 option data available all the time via the API, is a bad idea. It sounds like an awesome extension idea though.

**Comment by jtsternberg** [comment]
Ideally, the extension would create an api endpoint, and could look for a `'api-availability'` property on the `$cmb` object, which could take `'all'` (which would expose all the `$cmb->fields` options), or `'selective'` (which would require you to add `'api-availability' => true` to your field config).

**Comment by jtsternberg** [comment]
Re: WP-API options support: https://github.com/WP-API/WP-API/issues/816

**Comment by modemlooper** [comment]
^ yes yes with field config, we can do this now, don't need wp-api 2.0

**Comment by Ramblurr** [comment]
@modemlooper care to elaborate?

**Comment by Ramblurr** [comment]
Since I need this feature sooner rather than later, and I really like CMB, I've gone ahead and mashed up the WP-API and CMB2 APIs.

Creating a custom endpoint for CMB2 data is pretty simple. Just follow the [Extending AP-API with custom endpoints](http://wp-api.org/guides/extending.html) sample and in the `register_routes` function return the data you want from CMB2!

**Comment by modemlooper** [comment]
why was this closed? is api support not on the map?

**Comment by tnorthcutt** [comment]
@modemlooper I closed it based on @jtsternberg's [comments above](https://github.com/WebDevStudios/CMB2/issues/107#issuecomment-75960845), but I'm I'll reopen now for further discussion :smile:

**Comment by modemlooper** [comment]
I'm going to add WP-API support, was just waiting until the API was close to inclusion. Have option when creating fields 'show_in_rest' and it will plop that meta field to the API response.

**Comment by modemlooper** [comment]
placing this here as this is the method for adding the cab data http://v2.wp-api.org/extending/modifying/

**Comment by modemlooper** [comment]
Ok, so first half of WP-API is in core and the endpoints will be there soon enough. let's get show_in_rest args added to CBM fields.

Basically how it would work is when you create a CMB field there should be an arg 'show_in_rest => true and then we can create a method to get the fields with this arg and add to API

**Comment by jtsternberg** [comment]
[Work has begun!](https://github.com/WebDevStudios/CMB2/tree/cmb2-rest-api) Still working on the update part. Also, we may want a custom cmb2 endpoint or filter, for just getting the cmb2 data? or even retrieving a single cmb2 field?

**Comment by modemlooper** [comment]
An endpoint to send back all registered cmb fields would be nice.

**Comment by modemlooper** [comment]
working on the endpoints, the schema for post meta json is something that hasn't been set in stone. There is a meta endpoint for single post but what gets added to posts repsonse is not been determined.  The cool things about API is the data could be returned in any form but this is backwords for how people perceive WP. get_post_meta returns the same thing for everyone. I feel like the rest API sold do the same. This is sorta topic for WP-API community but putting it here so we get the schema right before release. 

Do we really want every single plugin to add another key in the json, that's what emponts are for. Does it need to specified its a CMB fields or merely post meta? 

    "cmb2:rest_demo_metabox":
        {
        "rest_demo_text": "this is to test rest data"
        },

or 

    "post_meta":
        {
        "rest_demo": {
            "renderd": "this is to test rest data"
            }
        },

**Comment by modemlooper** [comment]
"cmb2":
        {
           "rest_demo_metabox" {
               "rest_demo_text": {
                  "rendered": "this is to test rest data"
               }
             }
        },

**Comment by modemlooper** [comment]
Possible enpoints:

These are endpoints to get info about boxes and fields. Not the values.

wp-json/cmb2/v1/metaboxes // gets all registered show_in_rest metaboxes inlcuding fields
wp-json/cmb2/v1/fields // gets all register show_in_rest fields
wp-json/cmb2/v1/metaboxes/<metabox_slug> // gets single meta box and its fields
wp-json/cmb2/v1/fields/<field_slug> // gets a single field. 

?filter=post_type // filters registered show_in_rest metaboxes inlcuding fields for specified post type.

**Comment by modemlooper** [comment]
got the class up, just need to figure out the exact enpoints we want
https://github.com/modemlooper/CMB2/commit/d9f6e99e34a68341aa6febbe77a766529e2f47e0

**Comment by jtsternberg** [comment]
> This format would be easier to use

>    ```"cmb2":
>        {
>           "rest_demo_metabox" {
>               "rest_demo": {
>                  "rendered": "this is to test rest data"
>               }
>             }
>        },```

Agreed, we'll use that.

> `wp-json/cmb2/v1/metaboxes // gets all registered show_in_rest metaboxes inlcuding fields`

I'm trying to avoid the term metabox as much as possible these days as CMB2 is beyond metaboxes. I'm thinking `wp-json/cmb2/v1/boxes` would probably be my preferred endpoint.

> `wp-json/cmb2/v1/fields // gets all register show_in_rest fields`

I don't think there is value in mashing the fields together without the cmb2 object contextual data.

> `wp-json/cmb2/v1/metaboxes/<metabox_slug> // gets single meta box and its fields`

`wp-json/cmb2/v1/boxes/<box_slug>`

> `wp-json/cmb2/v1/fields/<field_slug> // gets a single field.` 

Field slugs are only unique within a single box. Will need to be: `wp-json/cmb2/v1/boxes/<box_slug>/fields/<field_slug>`

> `?filter=<post_type> // filters registered show_in_rest metaboxes inlcuding fields for specified post type.`

Agree, and probably can add an object-type filter, i.e.:

```
?filter=<object_type> // filters registered show_in_rest metaboxes inlcuding fields for specified object type (i.e. post, user, comment, term, options-page) 
```
(and maybe others, like filtering by field-type)

**Comment by modemlooper** [comment]
some test data in https://github.com/modemlooper/CMB2/commit/dbbc62a53d8493f66b750acdce99608889231519

![cmb2](https://cloud.githubusercontent.com/assets/867885/11017054/0ffa396c-8548-11e5-83ad-742e2288e115.png)

**Comment by jtsternberg** [comment]
Ryan, thanks for your work on this! I merged in what you had (minus some composer autoloader stuff?) and made a ton of updates: https://github.com/WebDevStudios/CMB2/commits/cmb2-rest-api

There's still some work to do (see the TODOs), but it's getting there!

**Comment by modemlooper** [comment]
Awesome! I have no idea where the composer stuff came from.

**Comment by jtsternberg** [comment]
## TODOS

### Add to the post endpoint:
- [ ] Add to the post endpoint
  - [ ] Make fields readable
    - [ ] Make fields honor show_in_rest property
  - [ ] Make fields writeable
    - [ ] Make fields honor show_in_rest property

### Add custom CMB2 namespace and endpoints:
- [ ] Add boxes endpoint
    - [ ] Make boxes honor show_in_rest property
    - [ ] Handle callable properties
- [ ] Add boxes/<cmb_id> endpoint
- [ ] Add boxes/<cmb_id>/fields endpoint
- [ ] Add boxes/<cmb_id>/fields/<field_id> endpoint
    - [ ] Make fields honor show_in_rest property
    - [ ] Handle callable properties

### Misc
- [ ] Research proper schema
- [ ] Properly document code
- [ ] Unit tests
- [ ] Documentation
    - [ ] Examples
- [ ] Research adding `_links` the proper way
- [ ] Use request objects helpers for getting `$_GET` parameters

**Comment by jtsternberg** [comment]
@modemlooper best bet is to re-fork the cmb2-rest-api branch rather than continue to work on yours.

**Comment by modemlooper** [comment]
K

**Comment by Mte90** [comment]
we waiting that support soon :-)

**Comment by JiveDig** [comment]
Since i've been playing with the API for a bit lately, I finally get why this is awesome... so, yeah... awesome. Looking forward to it. Thanks guys!

**Comment by JPry** [comment]
I've broken out the remaining items from [this comment above](https://github.com/WebDevStudios/CMB2/issues/107#issuecomment-156175070) into separate issues, all under the [REST API milestone](https://github.com/WebDevStudios/CMB2/milestones/REST%20API).

**Comment by jtsternberg** [comment]
Calling this done. Only thing left is documenting in the wiki (#618).
